// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQh3l27HxS2M7Bxou8yCDNg8Wru9JDy04',
    appId: '1:234998173945:web:50cc447287981e14ba1228',
    messagingSenderId: '234998173945',
    projectId: 'shopmanagementapp-f287d',
    authDomain: 'shopmanagementapp-f287d.firebaseapp.com',
    storageBucket: 'shopmanagementapp-f287d.appspot.com',
    measurementId: 'G-QN3NEXH9M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzJ9joUrNfqq9jDIt0x4vkWBoM6zLRyqM',
    appId: '1:234998173945:android:756499f00907e349ba1228',
    messagingSenderId: '234998173945',
    projectId: 'shopmanagementapp-f287d',
    storageBucket: 'shopmanagementapp-f287d.appspot.com',  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzIP8WGkMr2eVQ37w6YAUAyGJ9-eNw0jY',
    appId: '1:234998173945:ios:7f0a46f98ab3513eba1228',
    messagingSenderId: '234998173945',
    projectId: 'shopmanagementapp-f287d',
    storageBucket: 'shopmanagementapp-f287d.appspot.com',
    iosBundleId: 'com.example.shopmanagementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzIP8WGkMr2eVQ37w6YAUAyGJ9-eNw0jY',
    appId: '1:234998173945:ios:7f0a46f98ab3513eba1228',
    messagingSenderId: '234998173945',
    projectId: 'shopmanagementapp-f287d',
    storageBucket: 'shopmanagementapp-f287d.appspot.com',    iosBundleId: 'com.example.shopmanagementapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQh3l27HxS2M7Bxou8yCDNg8Wru9JDy04',
    appId: '1:234998173945:web:5586a60ff591b66bba1228',
    messagingSenderId: '234998173945',
    projectId: 'shopmanagementapp-f287d',
    authDomain: 'shopmanagementapp-f287d.firebaseapp.com',
    storageBucket: 'shopmanagementapp-f287d.appspot.com',
    measurementId: 'G-PGDQTRRHX2',
  );
}
